"use client";

import React, { useState, useEffect } from 'react';
import { FileText, Download, Lock, Loader2, FolderOpen } from 'lucide-react';
import { createClient } from '@/utils/supabase/client';

interface DocumentRow {
  id: string;
  title: string;
  type: string;
  file_url: string | null;
  generated_date: string | null;
}

export default function PortalDocuments() {
  const [documents, setDocuments] = useState<DocumentRow[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function loadDocs() {
      try {
        const supabase = createClient();
        const { data: { user } } = await supabase.auth.getUser();
        if (!user?.email) { setLoading(false); return; }

        // Resolve customer by email
        const { data: customer } = await supabase
          .from('customers').select('id').eq('email', user.email).maybeSingle();
        if (!customer) { setLoading(false); return; }

        // Fetch their documents
        const { data: docs } = await supabase
          .from('documents')
          .select('id, title, type, file_url, generated_date')
          .eq('customer_id', customer.id)
          .order('generated_date', { ascending: false });

        setDocuments(docs ?? []);
      } catch (err: unknown) {
        console.error('Failed to load documents', err);
      } finally {
        setLoading(false);
      }
    }
    loadDocs();
  }, []);

  if (loading) {
    return (
      <div className="p-8 flex items-center gap-3 text-gray-500">
        <Loader2 className="w-5 h-5 animate-spin" />
        Loading documents...
      </div>
    );
  }

  // Group documents by type
  const grouped = documents.reduce<Record<string, DocumentRow[]>>((acc, doc) => {
    const key = doc.type || 'Other';
    if (!acc[key]) acc[key] = [];
    acc[key].push(doc);
    return acc;
  }, {});

  const typeColor: Record<string, string> = {
    'Registration': 'bg-indigo-50 border-indigo-100',
    'Financial': 'bg-emerald-50 border-emerald-100',
    'Allocation': 'bg-blue-50 border-blue-100',
    'Legal': 'bg-amber-50 border-amber-100',
    'Other': 'bg-gray-50 border-gray-100',
  };

  return (
    <div className="p-4 md:p-8 max-w-4xl mx-auto space-y-6">
      <div className="flex items-center gap-3">
        <div className="p-3 bg-indigo-100 rounded-xl">
          <FolderOpen className="w-6 h-6 text-indigo-600" />
        </div>
        <div>
          <h1 className="text-2xl font-extrabold text-gray-900">Document Center</h1>
          <p className="text-gray-500 text-sm">
            Secure access to all your official files.
          </p>
        </div>
      </div>

      {documents.length === 0 ? (
        <div className="bg-white rounded-2xl border border-gray-200 shadow-sm p-12 text-center">
          <FileText className="w-12 h-12 text-gray-300 mx-auto mb-4" />
          <h3 className="text-gray-700 font-bold text-lg mb-1">No documents yet</h3>
          <p className="text-gray-400 text-sm">
            Your documents will appear here once they are generated by the office.
          </p>
        </div>
      ) : (
        Object.entries(grouped).map(([type, docs]) => (
          <div
            key={type}
            className={`rounded-2xl border shadow-sm overflow-hidden ${typeColor[type] ?? typeColor['Other']}`}
          >
            <div className="px-6 py-4 border-b border-inherit">
              <h2 className="font-bold text-gray-800 text-sm">{type} Documents</h2>
              <p className="text-xs text-gray-500">{docs.length} file{docs.length !== 1 ? 's' : ''}</p>
            </div>
            <div className="divide-y divide-white/60">
              {docs.map(doc => (
                <div key={doc.id} className="flex items-center justify-between px-6 py-3.5 bg-white/60 hover:bg-white/90 transition-colors">
                  <div className="flex items-center gap-3 min-w-0">
                    <FileText className="w-5 h-5 text-gray-400 flex-shrink-0" />
                    <div className="min-w-0">
                      <p className="text-sm font-bold text-gray-800 truncate">{doc.title}</p>
                      <p className="text-xs text-gray-400">
                        {doc.generated_date
                          ? new Date(doc.generated_date).toLocaleDateString()
                          : 'Date not set'}
                      </p>
                    </div>
                  </div>
                  {doc.file_url ? (
                    <a
                      href={doc.file_url}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="flex items-center gap-1.5 text-xs font-bold text-[var(--color-primary)] hover:underline flex-shrink-0 ml-4"
                    >
                      <Download className="w-3.5 h-3.5" />
                      Download
                    </a>
                  ) : (
                    <span className="flex items-center gap-1 text-xs text-gray-400 flex-shrink-0 ml-4">
                      <Lock className="w-3.5 h-3.5" />
                      Pending
                    </span>
                  )}
                </div>
              ))}
            </div>
          </div>
        ))
      )}
    </div>
  );
}
